### ISSUE TITLE
bug: professor dashboard fails to load student applications

### ISSUE THREAD

**Issue by joshuam1008** [rohanssrao/edu-setu#30] opened 2022-12-05 02:52 UTC
**Problem**
The professor's account is unable to view student applications. There is an "ORA-00918 column ambiguously defined" error.

**Steps to recreate**
1. Log in as a student
2. Apply to a professor's job posting
3. Log in as the professor of the job posting
4. Click `Applications` in the navbar
5. Observe "ORA-00918 column ambiguously defined" error

**Comment by david12white** [comment] 2022-12-05 02:53
Error fixed, but data not properly populating. Investigating.

**Comment by david12white** [comment] 2022-12-05 02:58
Error was caused by old data records in db- records deleted. Fixed in https://github.com/rohanssrao/edu-setu/commit/3b6bf085a715f808b48bca531ee791d1881e0253

**Closed as completed by david12white** 2022-12-05 02:58 UTC
Labels: bug
